### ISSUE TITLE
Module removes Edit Macro function on Hotbar.

### ISSUE THREAD

**Issue by Chelebi** [flamewave000/dragonflagon-arch#102]
**Describe the issue**
This is a weird one. For some Reason when enabling DF Architect in Foundry V9 it removes the Edit Macro function from the Hotbar when right Clicking a Macro 

**To Reproduce**
1. Enable DF Architect and the needed lib Modules
2. Create a Macro in the Hotbar
3. right click the Macro
4. be confused

**Expected behavior**
A Edit Macro function on right clicking the Macro

**Screenshots (Optional)**
DF Architect Off
![OFF](https://user-images.githubusercontent.com/1344472/148101610-d4589722-11b4-43c2-a032-819d82831356.jpg)

DF Architect On
![ON](https://user-images.githubusercontent.com/1344472/148101658-d64264c6-2b23-4b83-8cff-0328494f691a.jpg)

No error that i can see in the Console.

I tested if any other Module was causing it, after disabling all Modules it was Working fine, i started then enabling one after another and the Bug started to appear after enabling DF Architect.

**Comment by flamewave000** [comment]
DF Architect does not currently support V9. It is, however, in the process of being migrated. This issue will be covered by #97.

You can track the overall migration process here: [FoundryVTT V9 Migration](https://github.com/flamewave000/dragonflagon-arch/milestone/2)
