### ISSUE TITLE
Short summary of the issue...

### ISSUE THREAD

**Issue by dmrickey** [flamewave000/dragonflagon-arch#105]
**Describe the issue**
While DF Architect is enabled, I can no longer bring up the macro edtior

**To Reproduce**
1. Go to a world
2. Right click on a macro in your hotbar (if no macro exists create one)
3. You'll no longer see the edit option in the macro context menu

**Expected behavior**
I expect to see the edit option in the context menu.

Foundry v9 build 242
DF Architect 3.1.1

![image](https://user-images.githubusercontent.com/3664822/148850102-3dfd4e45-d4ac-4f69-8db1-6df2f63b52bd.png)
I did leave my library modules active otherwise Find the Culprit is a pain to work with. So I guess there is a possibility that it's a weird interaction just between DFA and one of these library modules. After running the Find the Culprit and disabling just this one mod the edit button popped back in as expected

**Comment by flamewave000** [comment]
DF Architect is not currently V9 compatible. Please follow the migration process here: [FoundryVTT V9 Migration](https://github.com/flamewave000/dragonflagon-arch/milestone/2)
