### ISSUE TITLE
Tiles flattening not working

### ISSUE THREAD

**Issue by oldeb** [flamewave000/dragonflagon-arch#106]
**Describe the issue**
When I select multiple tiles to create a single one, nothing happens when I click the "Flatten Tiles" button.

Foundry version : 9.242
Module version : 3.1.1

**To Reproduce**
1. Install brand new Foundry v9 instance
2. Install DF Architect module
3. Create a bunch of tiles with images
4. Select tiles
5. Click the "Flatten Tiles into Single Image" button in the toolbar
6. Click the "Flatten Tiles" button

**Expected behavior**
A new image with the selected tiles combinaison should be created.

**Actual behavior**
Nothing happens. When retying, a warning message telling that a capture session is already in progress appears.

**Screenshot**
![Capture](https://user-images.githubusercontent.com/6594118/148964640-6e0e4164-10e6-4834-9f62-3cf28e0b6ae6.PNG)

**Comment by flamewave000** [comment]
DF Architect 3.1.x does not support Foundry V9. Please wait for DF Architect v3.2.x.
You can follow the progress here: [FoundryVTT V9 Migration](https://github.com/flamewave000/dragonflagon-arch/milestone/2)
