### ISSUE TITLE
Not installable

### ISSUE THREAD

**Issue by ksingvo** [flamewave000/dragonflagon-arch#112]
**Describe the issue**
Due to door bug, tried to install the latest version of DF Architect.
But using https://github.com/flamewave000/dragonflagon-arch/blob/master/module.json fails

The manifest file "https://dragonflagon.cafe/mods/man/df-architect" referenced in module.json is still for old DF Architect version 3.1.1 and thats why installation might fail.

**To Reproduce**
1. Open Foundry VTT Setup
2. Click on 'Modules'
3. Click on Manifest-URL
4. Input: https://github.com/flamewave000/dragonflagon-arch/blob/master/module.json
5. See error: The request to "https://github.com/flamewave000/dragonflagon-arch/blob/master/module.json" did not provide a valid manifest file

**Screenshots (Optional)**
![Screenshot from 2022-01-18 23-50-38](https://user-images.githubusercontent.com/24297496/150031533-37f83815-6aaa-44c6-b71d-801ce2e19056.png)

**Comment by flamewave000** [comment]
DF Architect v3.2 has not been released for public yet, and v3.1.1 is not FoundryVTT V9 compatible.

**Comment by flamewave000** [comment]
You can follow the migration milestone progress here: [FoundryVTT V9 Migration](https://github.com/flamewave000/dragonflagon-arch/milestone/2)

**Comment by ksingvo** [comment]
Ah! Thanks, didn't know.
Though that the door glitching issue (#107) was worth a public release.
But I appreciate your opinion here.
