### ISSUE TITLE
Alt Grid Snap Icon issue when "Place on Main Control Bar" checked

### ISSUE THREAD

**Issue by Shuggaloaf** [flamewave000/dragonflagon-arch#117]
Seems fitting that I am the one reporting this issue as I am also the one who originally requested the option to place the grid-snap button on the main toolbar instead of each sub toolbar back in Issue #25. 

With above option checked the toggle button is placed to the right of all toolbar icons and is un-clickable. 

Foundry V9.255
Dnd5e 1.5.7
DF Arch 3.2.2

**To Reproduce**
See screenshots below but basically just turn that option on/off. 

**Screenshots**
With "Place on Main Control Bar" selected:
![image](https://user-images.githubusercontent.com/79543184/157485394-af531528-1511-438f-aab4-0ba1f1f87bd8.png)

Without option selected:
![image](https://user-images.githubusercontent.com/79543184/157485637-5b8a9992-42da-491e-bd94-ed91bcd236e0.png)

**Comment by flamewave000** [comment]
This must be a V9 issue I didn't catch when I was migrating the module.

**Comment by Shuggaloaf** [comment]
No worries. Easy work-around for now just by turning off that option. Low priority for sure.
