### ISSUE TITLE
Allow changing wall type via hotkey mid-drag

### ISSUE THREAD

**Issue by manuelVo** [flamewave000/dragonflagon-arch#119]
**Describe the issue**
When changing the wall type via a hotkey while a new wall is currently being drawn, the type of that current wall will not be updated. The changed wall type will only take effect for the next wall.

**To Reproduce**
1. Enable "Lock Wall Chaining"
2. Click and drag to place a wall
3. Let go of the mouse cursor to place the wall → wall chaining will cause a new wall to immediately attach to the mouse cursor
4. Change the selected wall type via a hotkey
5. The wall that's currently being drawn will retain the old type, even tough the wall type has been changed

**Expected behavior**
The wall that's still being drawn and hasn't been fully placed yet should adjust its type to the newly selected wall type.

**Comment by flamewave000** [comment]
I've adjusted your ticket to be a feature request as this was not an intended behavior. However, I think it's an excellent idea to add this to the module 👍🏼
