### ISSUE TITLE
Framerate issue

### ISSUE THREAD

**Issue by ravingdragoon** [flamewave000/dragonflagon-arch#121]
**Describe the issue**
When I have DF Architect enabled my framerate goes from 60+ to about 7.5 - 10.

**To Reproduce**
Install and enable DF Architect and its dependencies in Foundry on Google Chrome. See framerate tank.

**Expected behavior**
The framerate to be unaffected by DF Architect.

**Additional information**
I am hosted by The Forge. There are no issues or warnings in the Dev Console.

https://user-images.githubusercontent.com/72875320/160447959-e25e315d-08a6-4b97-8b4e-beb18a1a3461.mp4

https://user-images.githubusercontent.com/72875320/160447979-0934ac58-bee7-44fe-932d-8741a0cb4d7d.mp4

Debug Report
```Versions:
  Foundry: 9.255
  System: dnd5e version 1.5.7
User:
  Role: GAMEMASTER
Settings:
  Disable_Canvas: Disabled
  Max_FPS: 60
  Token_Drag_Vision: Disabled
  Performance_Mode: 0
  Token_Vision_Animation: Enabled
  Light_Source_Animation: Enabled
  Zoomed_Texture_Antialiasing: Disabled
  Animate_Roll_Tables: Enabled
Scene:
  Walls: 165
  Lights: 1
  Tokens: 0
  Tiles: 7
  Sounds: 0
  Drawings: 18
  Notes: 12
  Dimensions: 5825 x 3950
  Background: 3825 x 2550
  Foreground: 3832 x 2555
WebGL:
  Context: WebGL2RenderingContext
  GL_Vendor: WebKit
  Renderer: WebKit WebGL
  Unmasked_Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.15.1179)
  WebGL_Version: WebGL 2.0 (OpenGL ES 3.0 Chromium)
  MAX_TEXTURE_SIZE: 16384
  MAX_RENDERBUFFER: 16384
Database:
  Actors: 92
  Items: 26
  Scenes: 3
  Journals: 427
  Tables: 10
  Chat: 64
  Macros: 383
Data_Sizes:
  Actors: 904.73 KB
  Items: 375.4 KB
  Scenes: 77.97 KB
  Journals: 4.35 MB
  Tables: 29.12 KB
  Chat: 130.04 KB
  Macros: 672.73 KB
Browser:
  Platform: Win32
  Vendor: Google Inc.
  Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82
Memory:
  Heap_Limit: 4 GB
  Heap_Total: 152.83 MB
  Heap_Used: 120.64 MB
Modules:
  Total: 474
  Enabled: 14
Active_Modules:
  _chatcommands: Library: Chat Commands v1.4.0
  _document-sheet-registrar: Lib: Document Sheet Registrar v1.0.0
  arbron-context-menus: Arbron’s Context Menu Library v0.2.2
  colorsettings: lib - Color Settings v2.8.4
  debug-report: Debug Report Generator v0.1.3
  df-architect: DF Architect v3.2.2
  find-the-culprit: Find the culprit v1.4.0
  lib-captions: libCaptions v0.1.4
  lib-changelogs: Changelogs & Conflicts v0.7.7
  lib-df-buttons: Library: DF Module Buttons v1.0.2
  lib-wrapper: libWrapper v1.12.4.0
  module-sets: Module Sets - Dual Track GMing, baby v1.0.1
  socketlib: socketlib v1.0.10
  forge-vtt: The Forge v1.10
```

**Comment by flamewave000** [comment]
This sounds like it might be a module conflict type issue. Could you try running the Find The Culprit but keep the DF Architect turned on. I'm unable to reproduce this issue. With my current game server of 80+ modules enabled, I'm still getting 60fps with DF Architect.

**Comment by ravingdragoon** [comment]
This was with Find the Culprit active plus the modules below:
```
  _chatcommands: Library: Chat Commands v1.4.0
  _document-sheet-registrar: Lib: Document Sheet Registrar v1.0.0
  arbron-context-menus: Arbron’s Context Menu Library v0.2.2
  colorsettings: lib - Color Settings v2.8.4
  debug-report: Debug Report Generator v0.1.3
  df-architect: DF Architect v3.2.2
  find-the-culprit: Find the culprit v1.4.0
  lib-captions: libCaptions v0.1.4
  lib-changelogs: Changelogs & Conflicts v0.7.7
  lib-df-buttons: Library: DF Module Buttons v1.0.2
  lib-wrapper: libWrapper v1.12.4.0
  module-sets: Module Sets - Dual Track GMing, baby v1.0.1
  socketlib: socketlib v1.0.10
```

**Comment by ravingdragoon** [comment]
It is still happening using Find the Culprit and the modules below active:

  colorsettings: lib - Color Settings v2.8.4
  debug-report: Debug Report Generator v0.1.3
  df-architect: DF Architect v3.2.2
  find-the-culprit: Find the culprit v1.4.0
  lib-wrapper: libWrapper v1.12.4.0
  forge-vtt: The Forge v1.10

**Comment by flamewave000** [comment]
Alright, sadly I am unable to reproduce the issue using the same module list. If you have the time to try and do this, it might give me the information I need to figure out what's going on. I'm confused because I don't have any processes that run indefinitely, so if something like that is happening a Profiler might find it.

1. Open the Developer Tools (Press F12)
2. Click the "Performance" tab.
3. Make sure "Screenshots" is NOT checked (otherwise, it will make the result bloated with images)
4. Click the Record button
5. Wait about 10 seconds
6. Click the Stop button
7. Click the "Save Profile" button.

This should create a JSON file that you can then send to me here. As long as the screenshot option is disabled the file should only be about 3-5MB.

Obviously there's no rush, just send it when ever you have some time.

**Comment by ravingdragoon** [comment]
Figured it out. It is the Chrome Flag below:

Enable raw draw
When enabled, web content will be rastered on output surface directly.

**Comment by flamewave000** [comment]
huh, that sounds interesting. I tried turning the flag on for my chrome and it didn't seem to make any difference. Could be a difference of GPU between our computers and how Chrome handles it. But if you are no longer having the issue that is great! I'll go ahead and close the ticket, but just message here if there's any other issue related to this :+1:
