### ISSUE TITLE
Auto-Snapping not working

### ISSUE THREAD

**Issue by LorduFreeman** [flamewave000/dragonflagon-arch#122]
When ALT is held, the circle for Auto-Snap appears but the wall point does not snap to a point in range when releasing the mouse button.

Foundry V9 255
DnD5e 1.5.7
![image](https://user-images.githubusercontent.com/72170114/161966610-b2c1e32d-aed6-4e51-b815-6d258fd39b98.png)

Tested on a fresh world.

**Comment by flamewave000** [comment]
It looks like this issue only occurs when creating a new wall. Moving an already existing wall has no issue.
