### ISSUE TITLE
Players see light layer symbols

### ISSUE THREAD

**Issue by Weissrolf** [flamewave000/dragonflagon-arch#123]
**Describe the issue**
DF Architect causes player tokens to see the light layer symbols instead of lights.
v3.2.2 on build 269.

**To Reproduce**
1. Create light sources on map. 
2. Login as player and select their token.
3. Enable DF Architect  = player sees light sources symbols instead of lights.
4. Disable DF Architect  = player sees lights instead of light sources symbols. 

**Expected behavior**
Players should see lights instead of symbols.

**Screenshots (Optional)**
![grafik](https://user-images.githubusercontent.com/22069354/164887469-10235876-1275-4d29-9ae0-e132d8a1b3e2.png)

**Comment by flamewave000** [comment]
This is a feature which you have toggled on. Please refer to here in the documentation

https://github.com/flamewave000/dragonflagon-arch#see-wallslightssounds-on-other-layers

**Comment by Weissrolf** [comment]
I know about this useful feature and checked it right away, but the issue described here is different. The light symbols only show for **players** (hence the "Login as player" part), not for the GM and the feature you linked to is disabled.

**Comment by Weissrolf** [comment]
With this issue being closed, will it still be looked into?
