### ISSUE TITLE
DF Architect is leading to the Light Radius Boundaries constantly being on

### ISSUE THREAD

**Issue by Gray-Geist** [flamewave000/dragonflagon-arch#124]
I've tested with "Find the Culprit" module, which enables and disables mods until you find the problem mod and I've found that **DF Architect is leading to the Light Radius Boundaries constantly being on.** 

When I log in, I see the below:

![image](https://user-images.githubusercontent.com/76698563/165156795-c02691c3-207a-4ab8-849f-f804a2ad7d01.png)

A quick way to fix this is to switch from the current scene to another scene and then switch back, the lines are gone. But unfortunately upon selecting Lighting Controls, the light radius boundaries appear again and are not able to be toggled off. 

As you can see below, the "Display Light Boundaries on Other Layers" appears to be locked in "On". 

![image](https://user-images.githubusercontent.com/76698563/165157320-4fb8a248-07a7-48e5-9cc5-2d1845a26091.png)

Upon disabling DF Architect, I see the below (desired behavior):

![image](https://user-images.githubusercontent.com/76698563/165157488-fe7bc14b-b55a-4bbc-9fa2-f2978ca0037e.png)

Can you please lend a hand? :)

**Comment by flamewave000** [comment]
I have released v3.2.3 which has a small fix for this feature. I would appreciate it if you could try it out and report back if it fixes your issue.

**Comment by Gray-Geist** [comment]
It fixed the issue of stuck light boundaries on other layers but then it led to another issue, the opposite actually.

Now, on the same scene, when I select Lighting Controls --> Display Light Boundaries on other layers, and activate it, the toggle does not stick.  When I go to other layers, the light boundaries are not displayed. 

Comparatively when I go to Wall Controls --> Display Walls on other layers, and activate it, the toggle sticks. When I go to other layers, the walls are displayed.

But when I go to Wall Controls --> Display Walls on other layers, and activate it Walls, then go and activate Display Light Boundaries on other layers, the lights show up - _but only when "Display Walls on other layers" is active as well._
