### ISSUE TITLE
[SimpleFog]: Cannot Save Board Game Image with SimpleFog module enabled

### ISSUE THREAD

**Issue by strongpauly** [flamewave000/dragonflagon-arch#126]
**Conflicting Module(s)**
- SimpleFog

**Describe the conflict**
Console error when clicking Save Board Game Image:
```
CaptureGameScreen.ts:161 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'instance')
[Detected 1 package: df-architect]
    at CaptureGameScreen.ts:161:127
    at Array.map (<anonymous>)
    at Function.promptForCapture (CaptureGameScreen.ts:161:46)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43064)
    at HTMLButtonElement.v.handle (jquery.min.js:2:41048)
```

**Expected behavior**
Should launch Save Board Game Image dialog

**Comment by flamewave000** [comment]
Unfortunately Simplefog is very outdated. The entire scene layer system was revamped for V9, and I can't really support this legacy. But What I have done instead is add a detector for these legacy layers and essentially filter them out of the list of manageable layers. I also will print a warning to the console detailing the issue with the layer.
