### ISSUE TITLE
Foundry V.10 Console Issue

### ISSUE THREAD

**Issue by skellitor301** [flamewave000/dragonflagon-arch#135]
**Describe the issue**
LibWrapper detected an error with DF Architect

**Console Log**

== Technical Details: ==
Detected by libWrapper.
Package ID= df-architect
Error= Could not find target 'BackgroundLayer.prototype.activate': Could not find root scope 'BackgroundLayer'.

[Detected 1 package: df-architect]
    at ae (libWrapper-api.js:135:10)
    at se (libWrapper-api.js:152:19)
    at 🎁register [as register] (libWrapper-api.js:525:14)
    at TileCounter.ready (TileCounter.ts:8:14)
    at Object.fn (df-architect.ts:110:8)
(anonymous) @ df-architect.ts:110

**Comment by rtschaefer** [comment]
Is this module going to be compatible with v10 anytime soon? I really miss using it, but am concerned about bugs.

**Comment by nesretep** [comment]
I'm also seeing that error and a number of others when running this module.
