### ISSUE TITLE
Steal Monk's Double Click to split wall feature

### ISSUE THREAD

**Issue by CarlosFdez** [flamewave000/dragonflagon-arch#166]
**Describe the solution you'd like**
shamelessly

**Comment by flamewave000** [comment]
I appreciate the suggestion, but I don't really like to steal other people's features. Believe me when I say that I'd love to incorporate a couple of the features Ironmonk put into his Walls Enhancement module. Such as the "Drag Wall points together" feature.

**Comment by CarlosFdez** [comment]
Got it! Unfortunately they don't play too well together and there's a few bugs using them together. That said, for drag wall points together, I think you can get a different workflow that fits more natively if you made it work via holding alt rather than automatic with a toggle. Since holding alt is already "snap to point".
