### ISSUE TITLE
"X" in Crosshairs is slightly to the right off center

### ISSUE THREAD

**Issue by Shuggaloaf** [flamewave000/dragonflagon-arch#18]
Minor Issue. Probably wouldn't have noticed if I didn't already have my own custom cross-hairs icon. I wanted to make sure it wasn't mine,  that was off so I quickly flipped between them by repeatedly pressing shift. 

In this GIF you can see that it is the X. If you note the position of the 3 elements: your cross-hairs; my cross-hairs; and the semi-transparent box - you'll notice the 4 corners of the X (and therefore the center) are shifted right. 
EDIT: Possibly also down a slight bit as well.

Minor issue as I doubt anyone needs _that_ level of precision, but figured I'd mention since I noticed. 

WARNING - GIF shows flashing screen. Could possibly be a seizure trigger. 

https://user-images.githubusercontent.com/79543184/113789375-f8880e80-970c-11eb-884d-54d128eb496a.gif

**Comment by flamewave000** [comment]
That's a good catch 👍🏽 Looks like the coordinates when drawing the lines are just slightly off.
