### ISSUE TITLE
[SUGGESTION] Have Only One Alternative Grid Snap Icon

### ISSUE THREAD

**Issue by Shuggaloaf** [flamewave000/dragonflagon-arch#25]
The Alternative Grid Snap Icons/Toggles in each category changes the grid snap for _all_ categories. Since "one controls all", perhaps it would make more sense to have only 1 icon at the bottom of the main toolbar, instead of individual ones in each sub-toolbar. 
1.) Less Clutter.
2.) The default first-position icon (or in my case the "select everywhere" tool) would remain where it is. This allows lazy people like myself to not have to retrain muscle memory. ;-)

Not sure I'm explaining well so here's a thousand words:
![1](https://user-images.githubusercontent.com/79543184/113955919-a2899880-97ea-11eb-9fbc-789df63ce309.jpg)

**Comment by flamewave000** [comment]
I'm going to add a setting that will let you move it to the main Control Bar. I personally prefer the current location, but I'm fine with making it configurable 👍🏽

**Comment by Shuggaloaf** [comment]
Sorry for the delay but just wanted to say thanks for being versatile. Always good to have options!
