### ISSUE TITLE
DFA + Perfect Vision turns the map to black

### ISSUE THREAD

**Issue by MrVauxs** [flamewave000/dragonflagon-arch#31]
**Conflicting Module(s)**
- Perfect Vision

**Describe the conflict**
Upon loading the game, the maps are not loaded and unresponsive, pitch black and unable to click anything on any of them.

**Expected behavior**
Normal map behavior.

**(Optional) Screenshots**
![image](https://user-images.githubusercontent.com/32039708/114274930-e4038900-9a20-11eb-9886-c5c4d3b0202e.png)
![image](https://user-images.githubusercontent.com/32039708/114274931-e5cd4c80-9a20-11eb-9ef4-872ffa0bdfe0.png)

**(Optional) Additional context**
All issues have been recognized using Find the Culprit.
![image](https://user-images.githubusercontent.com/32039708/114274982-22994380-9a21-11eb-876b-fe37136102b4.png)

**Comment by dev7355608** [comment]
My mistake. It's not really a conflict. It's some broken code in PV that normally doesn't run but with DFA it does. So I never noticed my mistakes. I'll fix it right away.

**Comment by flamewave000** [comment]
@dev7355608 Thank you for looking into this, I'm happy PV and DFA can move past their disgruntled beginnings and be good friends 👍🏽🤣
