### ISSUE TITLE
Hotkeys allow non-GM users to access layers they should not have access to.

### ISSUE THREAD

**Issue by jessev14** [flamewave000/dragonflagon-arch#32]
**Describe the issue**
When player users press layer hotkeys, they are switched to that layer control, even if they should not have access to those layers (e.g. wall layer).

**To Reproduce**
1. Set Wall Controls Layer Keyboard Shortcuts in module settings.
2. On player user, press set hotkey for Wall Controls.
3. Observe that player is now on Wall Layer (though they still cannot make changes, due to permissions).

**Expected behavior**
Add a setting a to disable players from using hotkeys.
Alternatively, perform a check to see if the hotkey will send the player to a layer they are normally not allowed to get to,

**Comment by flamewave000** [comment]
I clearly made a terrible assumption that Foundry had checks to prevent access to those layers. Thank you for reporting the issue, I'll have to get a patch out to fix this security hole.
