### ISSUE TITLE
Error when Capturing Canvas

### ISSUE THREAD

**Issue by vlaminck** [flamewave000/dragonflagon-arch#38]
**Describe the issue**
Attempting to capture the canvas puts an error in the console, and permanently hangs on "Capturing Canvas..."

This is the error output in the console
```
Extract.ts:139 Uncaught RangeError: Invalid typed array length: 6370099200
    at new Uint8Array (<anonymous>)
    at t.canvas (Extract.ts:139)
    at t.base64 (Extract.ts:82)
    at df-architect.js:7
```

I'm using Chrome on a MacBook Pro

**To Reproduce**
1. Go to `Game Settings` Tab
2. Click on `Save Game Board Image` button
3. Choose `Entire Canvas` (see the attached screenshot for the settings that I used, but none of them seem to work for me)
4. Click `Capture Image` button
5. See the above error in the console

**Expected behavior**
An image is captured 

<img width="393" alt="save-game-board-image-options" src="https://user-images.githubusercontent.com/584771/116783705-f12afb00-aa55-11eb-8fbe-eccbb81ee068.png">

**Comment by vlaminck** [comment]
I believe this is due to the size of my scene. The dimensions are 8640x11520 (I know, I know it's too big). I was able to save a smaller scene without any issues.

**Comment by flamewave000** [comment]
This is indeed an issue with how large your scene is. You will need to render it in chunks. Increase the Horizontal split to 2 or 3 and it should be able to render it out. I'll keep this ticket open however as I should be catching that exception and reseting the canvas to avoid a lock up like you experienced.

**Comment by vlaminck** [comment]
When I split to 3, it downloaded 3 images of 0 bytes. I didn't try splitting to 4 and instead just use this script in the console. I still have to put them back together as layers in an image editor, but it works well. Thanks for the help.

```
function download_sprite_as_png(renderer, sprite, fileName) {
	renderer.extract.canvas(sprite).toBlob(function(b){
		var a = document.createElement('a');
		document.body.append(a);
		a.download = fileName;
		a.href = URL.createObjectURL(b);
		a.click();
		a.remove();
	}, 'image/png');
};

download_sprite_as_png(canvas.app.renderer, canvas.background, "background.png");
download_sprite_as_png(canvas.app.renderer, canvas.tiles, "tiles.png");
download_sprite_as_png(canvas.app.renderer, canvas.drawings, "drawings.png");
```
