### ISSUE TITLE
[Grid Scaler]: Generates multiple Alternate Grid Snap icons

### ISSUE THREAD

**Issue by deraviin** [flamewave000/dragonflagon-arch#43]
**Conflicting Module**
- Grid Scaler

**Describe the conflict**
Opening the grid scaler menu on foundry with DF Architect active causes multiple grid snaps to spawn in the menu, taking up a fair amount of the row.

**Expected behavior**
Only one grid snap icon should be necessary like in other menus.

**(Optional) Additional context**
Originally tested with Minimal UI, but pulled into a new world with only the two modules (and dependencies) active. There seems to be some odd interaction between Grid Scaler and other modules as turning on and off other modules caused the amount of extra grid snap icons to change in the grid scaler menu only.

**Screenshots**
![currentgameworld](https://user-images.githubusercontent.com/46595619/120907770-8d31be80-c621-11eb-8f83-a0341be97262.png) 
![newworldnoothermodules](https://user-images.githubusercontent.com/46595619/120907779-9d499e00-c621-11eb-8971-f7c44f6632b2.png)

**Comment by flamewave000** [comment]
What version of Foundry are you using?

**Comment by deraviin** [comment]
0.7.10 Foundry

**Comment by flamewave000** [comment]
Ok, thank you for reporting this issue I'll take a look, but I have already begun migration to 0.8.6. This fix will have to go in with that new update.

**Comment by flamewave000** [comment]
Ok so it looks like the Grid Scaler module has not made any new releases in a while and is not compatible for Foundry past 0.7.8. As such it is currently broken in 0.8.6. I will put this ticket on hold until Grid Scaler has a chance to update their module.

**Comment by flamewave000** [comment]
So it looks like they have released a new version for 0.8.x but they have not corrected the issue on their end. I've taken a look at the code used and it appears they are using a non-standard way to interface with Foundry's layer system. There's not really anything I can do at the moment.

The current solution is to toggle the option in settings to move the button to the main column of scene controls.
![image](https://user-images.githubusercontent.com/3588046/124018515-efc67200-d9b5-11eb-8ac4-ecca78fba8da.png)
