### ISSUE TITLE
Deleting a wall creates a graphical glitch

### ISSUE THREAD

**Issue by TheRarita** [flamewave000/dragonflagon-arch#45]
**Describe the issue**
When you delete a piece of the wall it will leave behind a graphical glitch that will keep the shadow of the wall still visible. Once you'll switch to different "tools" like token select, tiles, or drawings it will fix itself. It also gives an error to the console.

**To Reproduce**
1. Create a wall near a light source in a night setting
2. Delete the wall 
3. Sse the shadow still there

**Expected behavior**
The shadow should not render once the wall is deleted

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/51272447/120940549-26de9600-c71e-11eb-8624-51c18f6eff6a.png)
![image](https://user-images.githubusercontent.com/51272447/120940601-63aa8d00-c71e-11eb-8a63-429d47fbc4a0.png)
![image](https://user-images.githubusercontent.com/51272447/120940566-38c03900-c71e-11eb-923a-33fa2bfc0672.png)

**Comment by TheRarita** [comment]
Additionally, when trying to remove multiple segments at once it will only delete one and others are not deletable. This does not fix itself upon selecting a different tool. The walls still block light and movement.

Fixes itself upon F5-ing the browser window

![image](https://user-images.githubusercontent.com/51272447/120940739-0e22b000-c71f-11eb-8c60-c2a9322fbeb5.png)
![image](https://user-images.githubusercontent.com/51272447/120940749-1aa70880-c71f-11eb-9c0d-a90e6562973a.png)
![image](https://user-images.githubusercontent.com/51272447/120940756-24307080-c71f-11eb-8790-bbdee97743ae.png)

**Comment by flamewave000** [comment]
Thank you for reporting this and providing all these details! I'll get to work on fixing this now and push an update as soon as it's ready 👍🏽
