### ISSUE TITLE
Wall Chaining is Unreliable

### ISSUE THREAD

**Issue by webmaster94** [flamewave000/dragonflagon-arch#46]
When using the wall chaining lock, it does work but only if I quickly move to the next wall in the chain. If there is a delay of any significant length of time (approximately >3 seconds), the wall chaining stops and assumes normal foundry behavior of simply extending the length of the selected wall segment. Additionally, while wall chaining lock is active, it appears that the canvas does not drag when the mouse cursor is moved to the edge of the canvas view as it normally does when placing a wall. 

I would expect that if wall chaining lock is on when I click on a point of any wall at any time it will replicate the behavior had I held down Ctrl when I clicked on the point. Additionally, I would think the normal behavior for the foundry canvas would be replicated in this mode.

**Comment by flamewave000** [comment]
Thank you for the report. When I was testing it, I did not wait 3 seconds so I missed this issue. Also didn't try moving the screen. I'll have to reiterate over this feature and get it working properly again 👍🏼

**Comment by webmaster94** [comment]
No problem. I just noticed it because I generally work really closely to match it to the map and I sometimes will delay the next wall segment until I figure out exactly how I want to line it up. Thanks for taking a look.

**Comment by flamewave000** [comment]
Well I'm sure the new Auto-Snap feature will be useful for you then 👍🏽

**Comment by flamewave000** [comment]
I've tried testing this and cannot reproduce the issue. This could be a module conflict and not a bug. Let me know if this is still an issue for you.

If it is still occurring, please use the module [Find The Culprit!](https://foundryvtt.com/packages/find-the-culprit/) to see if there is a specific module that is causing the issue.
Please leave the following modules enabled when you do the test:
- `DF Architect` (obviously)
- `lib - Color Settings`
- `Library: DF Hotkeys`
- `libWrapper`

**Comment by flamewave000** [comment]
Closing this ticket due to inactivity. I'll reopen if you come back with some additional details 👍🏽
