### ISSUE TITLE
Light Templates do not show up after import with the module "macro folders"

### ISSUE THREAD

**Issue by spirritus** [flamewave000/dragonflagon-arch#47]
If you have macro folders enabled (a relay handy module) the light templates do not show up as macro after import.
Only  when disabling macro folders the imported templates are displayed.

**Comment by spirritus** [comment]
Crosspost https://github.com/earlSt1/vtt-macro-folders/issues/24

**Comment by spirritus** [comment]
This is not a df-architect issue.

**Comment by flamewave000** [comment]
@spirritus thank you for following up on this
