### ISSUE TITLE
Wall Splitting/Merging Not Functioning (0.8.8)

### ISSUE THREAD

**Issue by King-Khufu** [flamewave000/dragonflagon-arch#49]
**Describe the issue**
The wall merge and split tools do not appear to function on version 0.8.8. The other tools appear to function still.

**To Reproduce**
1. Go to scene
2. Create wall + select section
3. Click merge or split
4. Nothing happens to the wall

**Expected behavior**
It should either split or merge the selected wall segment.

**Active Modules**
1. Advanced Macros
2. Character Actions List dnd5e
3. Combat Enhancements
4. Combat Utility Belt
5. Compact DnDBeyond 5e Character Sheet
6. Compendium Folders
7. D&D Beyond Importer
8. Deprecated Modules
9. DF Architect
10. DF Curvy Walls
11. DFreds Droppables
12. DnD5e Helpers
13. Dynamic Active Effects
14. Easy Target
15. Fog Manager
16. FXMaster
17.  Initiative Double Click
18. Less Fog
19. lib - Color Settings
20. Library: DF Hotkeys
21. libWrapper
22. Magic Items
23. Michael Ghelfi Audio Pack
24. Midi QOL
25. Perfect Vision
26. Pings
27. Settings Extender
28. Skill Customizatio for D&D5e
29. socketlib
30. Split Journal
31. The Furnace
32. times-up
33. Token Action HUD
34. Token Mold
35. Wall Height

**Comment by foxreinhold** [comment]
Came here to report this exact thing.  Hopefully it gets fixed soon :) 
![image](https://user-images.githubusercontent.com/77173822/125224269-49267f00-e29b-11eb-8e1a-3cadd4cc1a4b.png)

**Comment by flamewave000** [comment]
This is likely a conflict with another module. The feature is working fine in my Foundry 0.8.8. Could you try using [Find The Culprit](https://foundryvtt.com/packages/find-the-culprit/) to narrow down which module might be causing the conflict?

**Comment by foxreinhold** [comment]
Sure will as soon as I get off work.

**Comment by foxreinhold** [comment]
Whatever module it was, must've updated itself.  Silly me updated all my modules (didn't pay attention to which updated) between last night and today, and now everything is fine.

**Comment by flamewave000** [comment]
I am very happy to hear that 👍🏽

**Comment by King-Khufu** [comment]
I just checked my 0.8.8 and I am still experiencing the issue, so I will go through the Find The Culprit when I have time tonight/later this week.

**Comment by King-Khufu** [comment]
I identified the issue (unless this is how it's always behaved and I've just not noticed prior)! The function does not work unless the scene you are working on is the **Active Scene**. I can replicate the error 100% of the time by working on an inactive scene. I have also confirmed this is the case by only having DF Architect and its required modules active.

**Comment by flamewave000** [comment]
Thank you for verifying this. I've also tried it locally and have seen the issue. I'll move forward using your more specific ticket 👍🏽
