### ISSUE TITLE
Wall splitting and join works only in active scene

### ISSUE THREAD

**Issue by arnoldn1** [flamewave000/dragonflagon-arch#50]
**Describe the issue**
Trying to split or join a wall in a scene that is not active fails. 

**To Reproduce**
On a new world with only DF Architect and its dependencies active:

- Create a new scene.
- View the new scene, but do not activate. 
- Create a wall in the scene.
- Select the wall and click the split button: fails.

- Set scene to active.
- Select the wall and click the split button: creates split.

Re-ordering / changing the priority of DF Architect and Lib-ColorSettings does not appear to make a difference.

**Expected behavior**
I would expect that walls can be split or joined in non-active scenes.

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/47816382/125430408-3dd25989-d1d5-496d-8fcc-4b67c21653c4.png)

**Comment by HippyCraig** [comment]
Im having the same issue, when its not active Im getting the following errors like the wall object doesn't exist but it does to select and delete it.

Uncaught (in promise) Error: The key Gpg6hbHaV4ufeakW does not exist in the EmbeddedCollection Collection
    at Map.get (collection.mjs:106)
    at ClientDatabaseBackend._preDeleteDocumentArray (foundry.js:8955)
    at ClientDatabaseBackend._deleteEmbeddedDocuments (foundry.js:8931)
    at ClientDatabaseBackend.delete (backend.mjs:214)
    at async Function.deleteDocuments (document.mjs:402)
backend.mjs:306 Foundry VTT | Deleted Wall with id [Gpg6hbHaV4ufeakW] in parent Scene [BjKuCKEioUyJ5nxE]
backend.mjs:306 Foundry VTT | Created Wall with id [0e14y5fFewhooAih] in parent Scene [BjKuCKEioUyJ5nxE]
collection.mjs:106 Uncaught (in promise) Error: The key 0e14y5fFewhooAih does not exist in the EmbeddedCollection Collection
    at Map.get (collection.mjs:106)
    at ClientDatabaseBackend._preDeleteDocumentArray (foundry.js:8955)
    at ClientDatabaseBackend._deleteEmbeddedDocuments (foundry.js:8931)
    at ClientDatabaseBackend.delete (backend.mjs:214)
    at async Function.deleteDocuments (document.mjs:402)
get @ collection.mjs:106
_preDeleteDocumentArray @ foundry.js:8955
_deleteEmbeddedDocuments @ foundry.js:8931
delete @ backend.mjs:214
Promise.then (async)
step @ df-architect.js:19
(anonymous) @ df-architect.js:19
__awaiter$4 @ df-architect.js:19
_splitWalls @ df-architect.js:19
_onClickTool @ foundry.js:27425
🎁call_wrapped @ libWrapper-wrapper.js:465
(anonymous) @ df-architect.js:27
(anonymous) @ df-architect.js:27
__awaiter$8 @ df-architect.js:27
🎁SceneControls.prototype._onClickTool#df-architect @ df-architect.js:27
🎁call_wrapper @ libWrapper-wrapper.js:574
🎁SceneControls.prototype._onClickTool#0 @ libWrapper-wrapper.js:162
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
collection.mjs:106 Uncaught (in promise) Error: The key 0e14y5fFewhooAih does not exist in the EmbeddedCollection Collection
    at Map.get (collection.mjs:106)
    at ClientDatabaseBackend._preDeleteDocumentArray (foundry.js:8955)
    at ClientDatabaseBackend._deleteEmbeddedDocuments (foundry.js:8931)
    at ClientDatabaseBackend.delete (backend.mjs:214)
    at async Function.deleteDocuments (document.mjs:402)

**Comment by flamewave000** [comment]
I'll also mention something I have noticed recently as well. The L and R labels do not update properly when the scene is not the active scene.

It appears to be that the non-active scene has many waking issues. I'll have to investigate and try to figure out why a scene acts so differently when it is not the active one.

**Comment by revilowaldow** [comment]
Same issue here, confirmed activating the scene functions as a temporary workaround.

![image](https://user-images.githubusercontent.com/52298102/129226521-792da30e-edb5-4791-9526-4b96c1b9e9d8.png)
