### ISSUE TITLE
Wall chaining is not working

### ISSUE THREAD

**Issue by rinnocenti** [flamewave000/dragonflagon-arch#54]
in new update chaining walls is not working.
not connect walls anymore.

**Comment by rinnocenti** [comment]
https://user-images.githubusercontent.com/3178127/131223224-f09f972d-4c4e-4d66-b2a9-fd2a9c904db3.mp4

It is expected that as the mouse extends the walls will project connected

**Comment by flamewave000** [comment]
Ahh I misunderstood. Wall Chaining is the general Foundry feature, so I thought you were saying I broke that core feature. The toggle button is the Wall Chain Lock. I'll take a look 👍🏼
