### ISSUE TITLE
TypeError: Cannot read property 'callbacks' of undefined

### ISSUE THREAD

**Issue by mkahvi** [flamewave000/dragonflagon-arch#56]
**Describe the issue**
Odd error on loading. Presumably due to missing scene, though there was notification about migration despite this being fresh new world.
```
df-architect.js:15 Uncaught (in promise) TypeError: Cannot read property 'callbacks' of undefined
[Detected 1 package: df-architect]
    at _WallCtrlInvert._patchWallsLayer (df-architect.js:15)
    at _WallCtrlInvert.ready (df-architect.js:15)
    at df-architect.js:37
    at Generator.next (<anonymous>)
    at fulfilled (df-architect.js:37)
```

**To Reproduce**
1. Load up

**Expected behavior**
No errors.

**Comment by flamewave000** [comment]
Not sure what was causing this, but I haven't seen it. Either way, I've rewritten the Wall Chain Lock feature, so hopefully this will be fixed for you in 2.1.2
