### ISSUE TITLE
[Forien's Quest Log]: Prevents Tile Flattener from Completing

### ISSUE THREAD

**Issue by typhonrt** [flamewave000/dragonflagon-arch#68]
Hi.. I just read in your update: 
```
Known Conflicts: The Tile Flattener feature does not work properly with the Levels module which does a lot of management of objects in a way that I am unable to interact with. If there are tokens or objects showing up in your image, you will have to disable Levels to get an accurate image capture.
Also appears to be an issue between Tile Flattener and Forien's Quest Log.
```

Can you describe what and how the apparent issue with FQL occurs? I can take a look, but would be glad to receive some reproduction steps if possible. Cheers.

**Comment by flamewave000** [comment]
Hey, I only just noticed the issue last night when I brought my update into my actual game server. I don't know the source just yet but I was planning to investigate it today. I've also been speaking with theripper about Levels and I hope to resolve the conflicts with both today. I'll reach out if I find any problems.

**Comment by flamewave000** [comment]
This conflict is corrected with this PR
https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log/pull/139
