### ISSUE TITLE
Allow light/wall count to be moved to lower right corner

### ISSUE THREAD

**Issue by foxreinhold** [flamewave000/dragonflagon-arch#72]
There's more than one mod (FPS Meter for example) that uses the upper right corner for something.  Perhaps it would be possible to allow DF architect to move it's counter to the lower right corner as a user configurable option?

![image](https://user-images.githubusercontent.com/77173822/135471598-20609a70-a2a4-419d-b974-3e500e2de75f.png)

**Comment by flamewave000** [comment]
I'm going to add some logic to make the counter move down to below the FPS counter if it is there.
