### ISSUE TITLE
Tile Flattener Not Working

### ISSUE THREAD

**Issue by samgrieve** [flamewave000/dragonflagon-arch#73]
Installed the module to try the Tile Flattener for improving performance on scenes built inside of Foundry. Upon trying to Flatten Tiles nothing happens and the following is outputted to the console.

Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'visible')
[Detected 1 package: df-architect]
    at Function.<anonymous> (df-architect.js:39)
    at Generator.next (<anonymous>)
    at fulfilled (df-architect.js:39)

The count for lights/walls/tiles also appear to overlap each other and do not disappear, each adding their own console error

TypeError: An error occurred while rendering CounterUI 2: Cannot read properties of undefined (reading 'offsetTop')
    at CounterUI.<anonymous> (df-architect.js:41)
    at Generator.next (<anonymous>)
    at fulfilled (df-architect.js:41)

**Comment by flamewave000** [comment]
Do you have Forien's Quest Log installed? If so, this is a known issue and FQL will be releasing a fix for it on their side.
https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log/pull/139

**Comment by samgrieve** [comment]
I do indeed! That will teach me for not checking the closed issues first!

**Comment by flamewave000** [comment]
No problem. Just disable it and let me know if your problem is fixed. I use the FQL module myself, so it's just a minor hassle to disable it while using Tile Flattener until typhonrt can release the fix

**Comment by samgrieve** [comment]
Disabled FQL but still have the same problems with both errors from the original post

**Comment by flamewave000** [comment]
Ok, I've actually been able to find the issue. I'll get a fix out shortly 👍🏽

**Comment by Bfrench6** [comment]
Yes, in 3.0.4 as well

**Comment by FGiorgi** [comment]
I know the issue is closed but I´m having the same identical problem. QFL is disabled, it gives me the same console error and the saving prompt dialogue never pops up.
Latest version of the module.
