### ISSUE TITLE
Wall Type Switching Error

### ISSUE THREAD

**Issue by Chelebi** [flamewave000/dragonflagon-arch#84]
So since a couple days now i have the problem that, when trying to Switch multiple walls to another type i get the error "The walls Datastore is not yet connected" and idk what that means, switching walls one by one works find just when i try to switch more than one at once i get this message and the walls don't switch type.

it was working fine before and idk what changed.

![image](https://user-images.githubusercontent.com/1344472/140988209-66c60d24-1302-4a9f-bed3-4fc8a8f6a2d5.png)

**Comment by flamewave000** [comment]
Thanks for reporting this. Someone had mentioned it on the Foundry Discord, but it's very useful to have a ticket for it. I'm running through tickets in some of my other modules at the moment, but I'll certainly get to this one as that's a feature I personally enjoy using 👍🏽

**Comment by Chelebi** [comment]
thanks for your hard work and for making such an amazing module, it really helps GM's prepping maps much faster <3
if you need any more info or if there is a way i can assist in identifying the problem pls let me know.
