### ISSUE TITLE
Doors not loading

### ISSUE THREAD

**Issue by slayer1551** [flamewave000/dragonflagon-arch#87]
**Describe the issue**
After updating to v9 doors no longer appear on the map

**To Reproduce**
Enable addon and the doors disappear. GM or player dont see doors anymore and can move freely

**Expected behavior**
Not have doors disappear

**Screenshots (Optional)**
Here is with the module enabled
![image](https://user-images.githubusercontent.com/875752/147122703-4c0ef91e-b321-4577-861e-fd97b2a72548.png)
And here it is disabled
![image](https://user-images.githubusercontent.com/875752/147122838-56548ff8-6d39-473f-b63a-6b7983f729cb.png)

**Comment by jgnoel86** [comment]
Seeing this same issue occur in our world.

**Comment by flamewave000** [comment]
DF Architect does not currently have V9 support.
